# Generated by Django 5.0.6 on 2024-06-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='poem',
            old_name='date_updated',
            new_name='updated',
        ),
    ]
